# Generated by Django 3.0.8 on 2020-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200712_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='score_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
